import {
  ResponsiveContainer,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  XAxis,
  YAxis,
  CartesianGrid,
} from "recharts";
import type { DashboardSession } from "../../../../../shared/types/DashboardSession";
import StatCardComponent from "./stat-card-component-for-dashboard/StatCardComponent";
import { Link } from "react-router-dom";
import { STATUS_COLORS } from "../../../const/statusColors";
import { MOOD_COLORS } from "../../../const/moodColors";
import { formatDuration } from "../../../helper/formatDuration";
import "./DashboardComponent.css";
import { muiThemeStyles } from "../../../../../shared/const/muiThemeStyles";
import { useState } from "react";
import { Box, Dialog, DialogContent, DialogTitle, ListItemButton, ListItemText, Typography, Card, CardContent, Chip, Stack} from "@mui/material";
import { useNavigate } from "react-router-dom";
import { formatDistanceToNow } from "date-fns";

export type DashboardComponentProps = {
  dashboard: DashboardSession;
};

export default function DashboardComponent({
  dashboard,
}: DashboardComponentProps) {

  const [openDueSessionsModal, setOpenDueSessionsModal] = useState<boolean>(false);
  const navigate = useNavigate();

  const statusData = Object.entries(dashboard.statusBreakdown).map(
    ([status, count]) => ({
      status,
      count,
    }),
  );

  const moodData = Object.entries(dashboard.moodBreakdown).map(
    ([mood, count]) => ({
      mood,
      count,
    }),
  );
  
  if (!dashboard) {
    return <span>No dashboard data</span>;
  }

  const recentSessionsLength = dashboard.latestSession.length;

  const openDueModal = () => {
    setOpenDueSessionsModal(true);
  };

  return (
    <div className="dashboard-wrapper">
      {/* Dashboard Header Section */}
      <section className="dashboard-header-section">
        <div className="dashboard-header-top">
          <h1 className="dashboard-title">
            {" "}
            <strong> Session's</strong> Dashboard{" "}
          </h1>
          <p className="dashboard-title-sub">
            <span className="track"> Track </span> your productivity and
            <strong> session </strong>
            <span className="performance"> performance</span>
          </p>
        </div>

        <div className="header-progress-container">
          <span className="overall-progress"> Overall Progress </span>
          <div
            className="progress-fill"
            style={{
              width: `${Math.min(Math.max(dashboard.overallProgressStatus, 0), 100)}%`,
            }}
          />
          <div className="progress-percentrage">
            {" "}
            <strong> {dashboard.overallProgressStatus}% </strong>
          </div>
        </div>
      </section>

      {/* KPI SECTION */}
      <section className="stats-grid-container">
        <StatCardComponent
          icon="📚"
          value={dashboard.total === 0 ? "Get started by creating your first session" : dashboard.total}
          label="Total sessions"
          tooltipDescription="Total number of sessions created"
        />

        <StatCardComponent
          icon="🎯"
          value={dashboard.completionRate === 0 ? "No completed sessions yet" : dashboard.completionRate.toFixed()}
          label="Completion Rate"
          tooltipDescription="Percentage of sessions that reached completed status."
        />

        <StatCardComponent
          icon="⏱️"
          value={dashboard.totalDuration === 0 ? "No tracked time yet" : formatDuration(dashboard.totalDuration)}
          label="Total Duration"
          tooltipDescription="Combined duration of all sessions."
        />

        <StatCardComponent
          icon="⚡"
          value={dashboard.averageSession === 0 ? "Average duration unavailable" : formatDuration(dashboard.averageSession)}
          label="Average Session"
          tooltipDescription="Average duration per session."
        />

        <StatCardComponent
          icon="🔥"
          value={dashboard.activityLength === 0 ? "No activity recorded yet" : dashboard.activityLength}
          label="Activity Length"
          tooltipDescription="Total number of activity records generated by session updates."
        />

        <StatCardComponent
          icon="⚠️"
          value={dashboard.upcomingDeadlines === 0 ? "No upcoming deadlines" : dashboard.upcomingDeadlines}
          label="Upcoming deadlines"
          tooltipDescription="Sessions with due dates approaching soon."
        />
        
        <Box
          onClick={openDueModal}
          sx={{
          cursor: "pointer",
          "& > *": {
          transition: "all 0.2s ease",
          },
          "&:hover > *": {
          transform: "translateY(-2px)",
          },
          }}
          >
            <StatCardComponent
            icon="⚠️"
            value={dashboard.overdueSessions.length === 0 ? "No overdue sessions" : dashboard.overdueSessions.length}
            label="Overdue sessions"
            tooltipDescription="Sessions with overdue sessions."
        />

        <Dialog
        open={openDueSessionsModal}
        onClose={() => setOpenDueSessionsModal(false)}
        maxWidth="sm"
        fullWidth
        slotProps={{
         paper: {
        style: {
          backgroundColor: "var(--card-bg)",
          border: "1px solid var(--border-color)",
          borderRadius: "1rem",
          },
        },
      }}
      >
        <DialogContent>
  <Typography
    variant="caption"
    color="text.secondary"
    sx={muiThemeStyles.heading}
  >
    Press Esc to close this window
  </Typography>

  {/* sessions list */}
</DialogContent>
          <DialogTitle
            sx={{
              ...muiThemeStyles.title,
              borderBottom: "1px solid var(--border-color)",
            }}
          >
            Overdue Sessions
          </DialogTitle>
          <DialogContent
            sx={{
              p: 0,
              backgroundColor: "var(--card-bg)",
            }}
          >
            {dashboard.overdueSessions.map((s) => (
            <ListItemButton
            key={s.id}
            onClick={() => {
              navigate(`/sessions/${s.id}`);
              setOpenDueSessionsModal(false);
            }}
            sx={{
              ...muiThemeStyles.actionButton,

              justifyContent: "center",
              textAlign: "center",

              borderBottom: "1px solid var(--border-color)",

              "&:last-child": {
                borderBottom: "none",
              },
            }}
          >
               <ListItemText
  primary={
    <span
      style={{
        color: "var(--text-primary)",
        fontWeight: 600,
      }}
    >
      {s.title}
    </span>
  }
  secondary={
    <span
      style={{
        color: "var(--text-muted)",
      }}
    >
      {s.dueDate
        ? new Date(s.dueDate).toLocaleDateString()
        : "No due date set"}
    </span>
  }
/>
                
              </ListItemButton>
            ))}
          </DialogContent>
        </Dialog>
      </Box>



        
        
      </section>

      {/* Analytics */}
      <section className="analytics-grid">
        {/* STATUS BAR CHART */}
        <article className="chart-card">
          <h2>Status Breakdown</h2>

          <ResponsiveContainer width="100%" height={300}>
            <BarChart
              data={statusData}
              margin={{
                top: 20,
                right: 20,
                left: 0,
                bottom: 40,
              }}
            >
              <CartesianGrid strokeDasharray="3 3" />

              <XAxis
                dataKey="status"
                interval={0}
                angle={-30}
                textAnchor="end"
                height={70}
              />

              <YAxis />

              <Bar dataKey="count" radius={[6, 6, 0, 0]}>
                {statusData.map((entry) => (
                  <Cell
                    key={entry.status}
                    fill={
                      STATUS_COLORS[entry.status as keyof typeof STATUS_COLORS]
                    }
                  />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </article>

        {/* MOOD PIE CHART */}
        <article className="chart-card">
          <h2>Mood Breakdown</h2>

          <ResponsiveContainer width="100%" height={300}>
            <PieChart>
              <Pie
                data={moodData}
                dataKey="count"
                nameKey="mood"
                outerRadius={100}
              >
                {moodData.map((entry) => (
                  <Cell
                    key={entry.mood}
                    fill={MOOD_COLORS[entry.mood as keyof typeof MOOD_COLORS]}
                  />
                ))}
              </Pie>

              <Tooltip
                contentStyle={muiThemeStyles.tooltip}
                labelStyle={muiThemeStyles.tooltipLabel}
                itemStyle={muiThemeStyles.tooltipItem}
              />
              <Legend />
            </PieChart>
          </ResponsiveContainer>
        </article>
      </section>

      {/* Recent Sessions */}
      <section className="recent-session">
        {dashboard.latestSession.length === 0 ? (
          <div className="empty-state">
            <span className="empty-text">No recent sessions found</span>
            <Link to="/sessions/create">Create Your First Session</Link>
          </div>
        ) : (
          <div>
            <h2 className="session-length">
              Recent Sessions Added
              <span className="session-count">
                ({recentSessionsLength}) of {dashboard.total}
              </span>
            </h2>
            <Stack spacing={2}>
            {dashboard.latestSession.map((d) => (
 <Card
  key={d.id}
  onClick={() => navigate(`/sessions/${d.id}`)}
  sx={{
    ...muiThemeStyles.paper,
    cursor: "pointer",
  }}
>
  <CardContent
    sx={{
      display: "flex",
      flexDirection: "column",
      gap: 1.5,
    }}
  >
    <Typography
      variant="h6"
      sx={muiThemeStyles.title}
    >
      {d.title}
    </Typography>

    <Chip
      label={d.status}
      size="small"
      sx={{
        ...muiThemeStyles.statusChip,
        alignSelf: "flex-start",
      }}
    />

    <Typography
      variant="body2"
      sx={muiThemeStyles.body}
    >
      Created {formatDistanceToNow(new Date(d.createdAt))}
    </Typography>

    <Typography
      variant="body2"
      sx={muiThemeStyles.muted}
    >
      {d.updatedAt
        ? `Updated ${formatDistanceToNow(
            new Date(d.updatedAt)
          )}`
        : "Never updated"}
    </Typography>
  </CardContent>
  
</Card>

))}
</Stack>
          </div>
        )}
      </section>


    </div>
  );
}
